import { Currency, CurrencyFormat } from "./market.types";

export namespace MarketConfig {
	export const CURRENCIES_FORMAT: Record<Currency, CurrencyFormat> = {
		BTC: {
			crypto: true,
			code: "BTC",
			symbol: "Ƀ",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 8,
		},
		ETH: {
			crypto: true,
			code: "ETH",
			symbol: "Ξ",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 8,
		},
		LTC: {
			crypto: true,
			code: "LTC",
			symbol: "Ł",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 8,
		},
		AUD: {
			crypto: false,
			code: "AUD",
			symbol: "A$",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		BRL: {
			crypto: false,
			code: "BRL",
			symbol: "R$",
			groupSeparator: ".",
			decimalSeparator: ",",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 2,
		},
		CAD: {
			crypto: false,
			code: "CAD",
			symbol: "C$",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		CHF: {
			crypto: false,
			code: "CHF",
			symbol: "CHF",
			groupSeparator: "'",
			decimalSeparator: ",",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 2,
		},
		CNY: {
			crypto: false,
			code: "CNY",
			symbol: "¥",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		EUR: {
			crypto: false,
			code: "EUR",
			symbol: "€",
			groupSeparator: " ",
			decimalSeparator: ",",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 2,
		},
		GBP: {
			crypto: false,
			code: "GBP",
			symbol: "£",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		HKD: {
			crypto: false,
			code: "HKD",
			symbol: "HK$",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		IDR: {
			crypto: false,
			code: "IDR",
			symbol: "Rp",
			groupSeparator: ".",
			decimalSeparator: ",",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 0,
		},
		INR: {
			crypto: false,
			code: "INR",
			symbol: "₹",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		JPY: {
			crypto: false,
			code: "JPY",
			symbol: "¥",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 0,
		},
		KRW: {
			crypto: false,
			code: "KRW",
			symbol: "₩",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 0,
		},
		MXN: {
			crypto: false,
			code: "MXN",
			symbol: "MX$",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
		RUB: {
			crypto: false,
			code: "RUB",
			symbol: "₽",
			groupSeparator: " ",
			decimalSeparator: ",",
			symbolOnLeft: false,
			spaceBetweenAmountAndSymbol: true,
			decimalDigits: 2,
		},
		USD: {
			code: "USD",
			crypto: false,
			symbol: "$",
			groupSeparator: ",",
			decimalSeparator: ".",
			symbolOnLeft: true,
			spaceBetweenAmountAndSymbol: false,
			decimalDigits: 2,
		},
	};
}
